<Project Sdk="Microsoft.Build.NoTargets/3.7.56">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PackageType>MSBuildSdk</PackageType>
    <PackageTags>MSBuildSdk</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Exclude target framework from the package dependencies as we don't include the build output -->
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <PropertyGroup>
    <Description>MSBuild .NET Sdk for Godot projects.</Description>
    <Authors>Godot Engine contributors</Authors>

    <PackageId>Godot.NET.Sdk</PackageId>
    <Version>4.8.0</Version>
    <PackageVersion>$(PackageVersion_Godot_NET_Sdk)</PackageVersion>
    <RepositoryUrl>https://github.com/godotengine/godot/tree/master/modules/mono/editor/Godot.NET.Sdk</RepositoryUrl>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) Godot Engine contributors</Copyright>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <TasksTopDirectory>..\Godot.NET.Sdk.Tasks\</TasksTopDirectory>
    <TasksOutputDirectory>$(TasksTopDirectory)Tasks\bin\$(Configuration)\</TasksOutputDirectory>
    <!--
    We need to put any MSBuild tasks anywhere but the lib\ folder, because they are not dependencies
    of the consuming project.
    However when packing, Nuget will warn us if it finds an assembly outside of the lib\ folder.
    We disable this warning.
    https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=visualstudio#bundle-dependencies-into-the-package
    -->
    <NoWarn>$(NoWarn);NU5100</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(TasksTopDirectory)Tasks\Godot.NET.Sdk.Tasks.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <!-- Package Sdk\Sdk.props and Sdk\Sdk.targets file -->
    <None Include="Sdk\Sdk.props" Pack="true" PackagePath="Sdk" />
    <None Include="Sdk\Sdk.targets" Pack="true" PackagePath="Sdk" />
    <!-- SdkPackageVersions.props -->
    <None Include="$(GodotSdkPackageVersionsFilePath)" Pack="true" PackagePath="Sdk">
      <Link>Sdk\SdkPackageVersions.props</Link>
    </None>
    <None Include="Sdk\Android.props" Pack="true" PackagePath="Sdk" />
    <None Include="Sdk\iOS.props" Pack="true" PackagePath="Sdk" />
    <None Include="Sdk\iOS.targets" Pack="true" PackagePath="Sdk" />

    <!-- Package task-related files -->
    <None Include="Sdk\Tasks.targets" Pack="true" PackagePath="Sdk" />
    <None Include="$(TasksTopDirectory)Tasks\targets\*.targets" Pack="true" PackagePath="tasks" />
    <None Include="$(TasksOutputDirectory)Godot.NET.Sdk.Tasks.dll" Pack="true" PackagePath="tasks" />

    <!-- Package string-caching related files. -->
    <None Include="$(TasksOutputDirectory)Godot.NET.Sdk.Tasks.StringCaching.dll" Pack="true" PackagePath="tasks" />
    <None Include="$(TasksOutputDirectory)Mono.Cecil.dll" Pack="true" PackagePath="tasks" />
    <None Include="$(TasksOutputDirectory)Mono.Cecil.Pdb.dll" Pack="true" PackagePath="tasks" />
  </ItemGroup>

</Project>
